### ISSUE TITLE
Unpackager cannot output into a Packager

### ISSUE THREAD

**Issue by malakai97** [TheLMiffy1111/PackagedAuto#11]
An Unpackager should be able to output into a Packager just like any other inventory. 

The reason someone would want to do this is the Unpackager is connected to the main network, but the Packager is on a subnet, such as one set up for parallelization of a crafting task. This would allow one to leverage the Unpackager's blocking mode to get recipe packages into the subnet.

This network-> Unpackager -> Packager setup removes the need for one to duplicate their packagedauto recipes with AE2 patterns.

You might be asking 'why not just use a chest in between?' Then the method to take items from the chest to the Packager would have to have intelligent blocking support that is fully aware of the recipes already encoded in the Unpackager.

**Comment by malakai97** [comment]
It comes to mind that a feature as simple a mode on the Unpackager that changes it to just be a passthrough--that is, it would only move the recipe package from its input slots to its output slots--would solve this need.

**Comment by TheLMiffy1111** [comment]
Sorry, I do not understand the use case.

**Comment by malakai97** [comment]
The goal is two-fold:

* Output recipe-packages into a chest. (We want to round-robin the recipe packages to a bank of machines from that chest.) 
* Create no AE2 patterns. This part is why we need to connect both a packager and unpackager to the AE network.

1. By connecting a Packager with a recipe holder to the AE network, the network learns how to craft those packages.
2. By connecting an Unpackager with a recipe holder to the AE network, the network learns how to craft each package into the thing it creates.
3. Thus, when we tell the network to create something, the unpackager will output the e.g. 7 items into its adjacent inventory.

This third step outputting items instead of recipe packages prevents us from reaching our goal.

By adding a fourth step, one can achieve the goal:

4. The adjacent inventory is another Packager not connected to the AE network, which takes the ingredients and outputs a recipe package. [This only works with blocking mode.]

**Comment by TheLMiffy1111** [comment]
Why would you not use AE2 patterns?

**Comment by malakai97** [comment]
I don't want to encode the same recipe twice, especially when I would need to repeat the process for 100+ recipes.
