### ISSUE TITLE
unpackager causing ticklag when packages are waiting in input slot

### ISSUE THREAD

**Issue by Dutchs** [TheLMiffy1111/PackagedAuto#12]
This is the case that triggers this issue:
![unpack](https://user-images.githubusercontent.com/1423624/64915050-6735fd80-d75e-11e9-9adb-551a8826ad4d.png)
It seems that more NBT data on the packages and more of them waiting to be unpackaged compound the issue, with the unpackager in the screenshot taking close to 5ms per tick according to LagGoggles (each package held close to 9 stacks of 48 items)

From a preliminary look with a profiler it seems to take the most time to process:
`thelm.packagedauto.recipe.RecipeInfoProcessing.readFromNBT()`

**Comment by TheLMiffy1111** [comment]
Is the lag on the client side or the server side?

**Comment by Dutchs** [comment]
serverside
![2019-09-14_02 42 14](https://user-images.githubusercontent.com/1423624/65373395-33d30180-dc7d-11e9-8284-ce7dfd18a61f.png)

**Comment by TheLMiffy1111** [comment]
This issue should be resolved by the version I just put out.
