### ISSUE TITLE
Option to ignore NBT?

### ISSUE THREAD

**Issue by pa-philos** [TheLMiffy1111/PackagedAuto#18]
Is there a way to ignore the NBT data from items? And Meta as well, some kind of fuzzy mode.

Thanks for this awesome mod!

**Comment by ReiDaTecnologia** [comment]
shame...

**Comment by TheLMiffy1111** [comment]
This issue was created for 1.12.2 when substitution was not possible.

**Comment by ReiDaTecnologia** [comment]
ye i saw it later in the changelogs, mb
