### ISSUE TITLE
[Feature Request] Running the packager without energy

### ISSUE THREAD

**Issue by DaedalusGame** [TheLMiffy1111/PackagedAuto#20]
The packager specifically checks for energy > 0 before it starts packaging, while the unpackager doesn't require any energy to be present to work at all. It would be cool if that check could be changed so that the entire mod can run without requiring energy.

**Comment by TheLMiffy1111** [comment]
Pretty sure both requires energy, but there should be config options to set the energy to 0, specifically "energy_req" in category "blocks.packager" and "energy_usage" in "blocks.unpackager"

**Comment by DaedalusGame** [comment]
i did set those config options to 0, hence me asking about the energy > 0 check to be changed.

**Comment by TheLMiffy1111** [comment]
Ok found it
https://github.com/TheLMiffy1111/PackagedAuto/blob/cbf0639eef49dcbf7556e01e083f0b44d79cf11c/src/main/java/thelm/packagedauto/tile/TilePackager.java#L156-L158
