### ISSUE TITLE
Pattern Dupe Bug w/ Extended Crafting Automation Interface

### ISSUE THREAD

**Issue by DanielGordon39** [TheLMiffy1111/PackagedAuto#22]
1.12.2-1.0.2.9 PackagedAuto
1.5.5 Extended Crafting
Enigmatica Expert 2 1.80

When the packager is next to the automation interface, w/ the interface set to pull items in, the input slot of the automation interface fills up with the pattern in the packager. Idk if this is a packaged auto bug or a automation interface bug but I was not seeing this using other inventories w/ the automation interface

**Comment by ALongStringOfNumbers** [comment]
The automation interface itself has a dupe bug on the last version available in 1.12.2. This dupe bug was since fixed in https://github.com/OmnifactoryDevs/ExtendedCrafting which is a fork of Extended Crafting for 1.12.2 made to fix several issues.
