### ISSUE TITLE
Cannot stack packages after server restart

### ISSUE THREAD

**Issue by Gammelkebab** [TheLMiffy1111/PackagedAuto#23]
I'm stock-crafting packages and some metadata on the packages seems to change when my server restarts, so they don't stack with newly created ones, leading to issues with interface stocking and level emitter detection in ae2.
![packagedauto](https://user-images.githubusercontent.com/7571721/80910788-47296d80-8d32-11ea-804a-2e3a5ff30de3.png)

NBT-Editor shows, that in the ingredients matrix, air is saved as ingredient. The amount appears to change sometimes.

**Comment by TheLMiffy1111** [comment]
Fixed
