### ISSUE TITLE
Recipe Encoder does not recognize OpenComputers cable.

### ISSUE THREAD

**Issue by NopeDK** [TheLMiffy1111/PackagedAuto#24]
OpenComputers "Cable" are not added to the Recipe Package in the Package Recipe Encoder:
![2020-06-10_15 13 49](https://user-images.githubusercontent.com/808397/84272540-d72ab600-ab2d-11ea-86f4-779fb248b787.png)

OpenComputers 1.7.5.192
PackagedAuto 1.12.2-1.0.3.12
PackagedExCrafting 1.12.2-1.0.1.1

DD&SS Modpack v. 7.4a

**Comment by TheLMiffy1111** [comment]
I think the issue has been fixed, but please update and test
