### ISSUE TITLE
[QoL Feature Request] Double inputs and outputs button on pattern encoder

### ISSUE THREAD

**Issue by Caedis** [TheLMiffy1111/PackagedAuto#29]
A button that allows the player to easily double the items (input and output) for the current recipe in the encoder.  
If either the input or output goes over a full stack, add another inventory slot for that item.

Example from PrototypeTrouser's fork of AE2
![image](https://user-images.githubusercontent.com/18713839/116793725-03c12680-aa8e-11eb-94ec-cc0d14bb2d66.png)

**Comment by TheLMiffy1111** [comment]
Added set stack size feature instead.
