### ISSUE TITLE
Cables only connecting when placed afterward

### ISSUE THREAD

**Issue by tornewuff** [TheLMiffy1111/PackagedAuto#3]
With AE2 rv6-stable-4 and PackagedAuto 1.12.2-1.0.0.2, the AE cables only appear to connect to the packager/unpackager if the cable is placed after the device. If the cable is already in place, putting down a packager/unpackager doesn't connect to the cable visually or appear on the network, and you have to break and replace the cable to get it to work.

**Comment by malakai97** [comment]
This happens with large AE2 networks that already experience long lag when adding cables to the network. Likely some sort of timeout is being hit.

**Comment by jk1895** [comment]
I have this annoying bug too. I place the unpacker and it is not connecting:
![2020-01-15_20 49 30](https://user-images.githubusercontent.com/20401451/72466360-07696500-37d9-11ea-9008-885ffcb46d80.png)
I place a new Cable and it is connecting:
![2020-01-15_20 49 40](https://user-images.githubusercontent.com/20401451/72466383-13552700-37d9-11ea-82a3-17beb7d253b7.png)
I break the unpacker, place it again and both cables are not connected.
![2020-01-15_20 49 51](https://user-images.githubusercontent.com/20401451/72466400-1b14cb80-37d9-11ea-95af-26d3a50293d0.png)

Please, can you check it again?

**Comment by TheLMiffy1111** [comment]
Should be fixed
