### ISSUE TITLE
The AE2 system does not detect certain packages correctly

### ISSUE THREAD

**Issue by zoller27osu** [TheLMiffy1111/PackagedAuto#39]
The cause is unclear, but in FTB University 1.16 (modpack version 1.3.0), attempting to auto-craft Ultimate Singularities results in the Packages being crafted and put in the ME System, but the crafting task/CPU does not detect them - they stay on the "Crafting" status.

Extracting the packages from the system and putting them in an Interface for re-import does not help with their detection.
The workaround is to put the Packages directly into the Unpackager and cancel the crafting task, but this is obviously pretty obnoxious.

**Comment by TheLMiffy1111** [comment]
After testing, it seems that sometimes packages created in this case somehow are not equal to the ones expected, looking into it

**Comment by TheLMiffy1111** [comment]
Cause is similar to #23 it seems

**Comment by TheLMiffy1111** [comment]
Should be fixed
