### ISSUE TITLE
Easier editing of recipe patterns?

### ISSUE THREAD

**Issue by tornewuff** [TheLMiffy1111/PackagedAuto#4]
It'd be nice if putting an already-programmed recipe pattern holder into the encoder loaded what was already in the holder (if non-blank) into the encoder, similarly to how the main AE2 pattern grid recalls the recipe if you put a programmed pattern back into the programming slot.

This would make it easier to edit existing patterns or add new patterns to the same pattern holder - right now the only easy way to do this is to keep the encoder placed in the world so it remembers the patterns, and to have more than one encoder if you want to program different pattern holders with different sets of patterns.

**Comment by TheLMiffy1111** [comment]
The ability of loading recipes from patterns into the encoder has been added in 1.0.1.3.
