### ISSUE TITLE
[qol] Remember the recipe type of the previous when encoding multiple recipes

### ISSUE THREAD

**Issue by nmay231** [TheLMiffy1111/PackagedAuto#41]
When encoding multiple recipes with the same recipe type (say, they are all Ultimate crafting table recipes), it can be tedious to switch the type each time before encoding the recipe. It would be convenient if the encoder block would remember the recipe type when switching to an empty recipe slot.

Thanks for all the mods you've made btw.

**Comment by TheLMiffy1111** [comment]
Added
