### ISSUE TITLE
1.7.10 CRASH

### ISSUE THREAD

**Issue by iamsoNewBee** [TheLMiffy1111/PackagedAuto#44]
[minecraft-exported-crash-info-2023-02-01T23-08-01.zip](https://github.com/TheLMiffy1111/PackagedAuto/files/10558517/minecraft-exported-crash-info-2023-02-01T23-08-01.zip)

**Comment by TheLMiffy1111** [comment]
The 1.7.10 version requires NotEnoughItems Unofficial.

**Comment by Deevate** [comment]
New NEI on 1.7.10 crashes when trying to view craft, for example, planks or chests. Will the mod be ported to the old NEI? It's just that if you use NEI ported from new versions, then many addons for the correct operation of NEI and mods (For example, Thaumcraft 4, Forestry and much more). If it is still ported, then finally I will be able to make crafts with more than 9 types of items in an extreme workbench :)
