### ISSUE TITLE
Ported new NEI crashes (Will mod be ported to old NEI?)

### ISSUE THREAD

**Issue by Deevate** [TheLMiffy1111/PackagedAuto#45]
New NEI on 1.7.10 crashes when trying to view craft, for example, planks or chests. Will the mod be ported to the old NEI? It's just that if you use NEI ported from new versions, then many addons for the correct operation of NEI and mods (For example, Thaumcraft 4, Forestry and much more). If it is still ported, then finally I will be able to make crafts with more than 9 types of items in an extreme workbench :)

**Comment by TheLMiffy1111** [comment]
Mod now loads with old NEI
