### ISSUE TITLE
Mods.toml wrong version

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/PackagedAuto#48]
![image](https://github.com/TheLMiffy1111/PackagedAuto/assets/146892171/4ecd1adf-ef5a-47a1-b3bb-64597f4d3aa1)
Doesnt let game to start if using addons

**Comment by TheLMiffy1111** [comment]
I've reuploaded the file, will take a while for it to get approved

**Comment by TheLMiffy1111** [comment]
The file is reuploaded
