### ISSUE TITLE
Able to summon arbitrary items in survival using PackagedAuto

### ISSUE THREAD

**Issue by Iris-xii** [TheLMiffy1111/PackagedAuto#50]
One might be able to use PackagedAuto to obtain arbitrary items. 

### Reproduction Steps

1. Encode a Cheap Item -> nothing PackagedAuto recipe:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/ca3fbc63-4060-4913-a241-5fddaabda11a)
A cheap item.
2. Encode a Target Item -> nothing PA recipe:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/a70af95f-5f76-440b-90bc-fa71f58f0074)
3. Hover over the package shown in the target item recipe and press 'A' to bookmark it to JEI.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/e869b65f-8c83-465e-927c-863e63fff2e9)
4. Encode another PA recipe of this bookmarked package -> nothing. 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/a8099240-e50b-44b7-a1d7-6f505ef45afb)
5. Save the patterns into a packaged recipe holder, and then put it on a (powered) Packager
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/e85072d5-73c5-48d7-b247-fb5e2dda5a93)
6. Put the cheap item into the packager. It'll get bundled into a package (probably intended behavior so far)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/56e1266e-0a37-4407-b8dc-2aa990bf95d9)
7. Grab the packages you just got and put them -back- into the packager. You will obtain a new package containing a package containing the target item (probably unintended behavior) 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/fcb8a5de-05d2-4ef5-a0ce-af98e57709f3)
7.1 (if step 7 doesn't work immediately, try clicking the button a few times)
![image](https://github.com/TheLMiffy1111/PackagedAuto/assets/48930896/ca98aed6-d306-4f3c-af72-0af132099b7a)
8. Shift-right-click the package obtained. You will get -another- package
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/ed973089-e2cb-47be-9c74-ef6af6e56170)
9. Shift-right-click that package you just got. Congratulations! You now have your Target Item!
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/b2f9197c-55fb-4525-9a40-e1fd6d731e13)

This seems to work for any items you're able to JEI-drag into the PA crafting grid, which is basically all of them. Oops.

Issue originally from https://github.com/Nomi-CEu/Nomi-CEu/issues/632

**Comment by TheLMiffy1111** [comment]
Will look into it

**Comment by TheLMiffy1111** [comment]
Fixed in 1.0.10.39, 2.0.5.28, 3.1.6.32, 3.2.4.21, 3.4.2.10

**Comment by Iris-xii** [comment]
Oh wow that was super fast, thank you!
