### ISSUE TITLE
Took ~7 seconds to init runtime plugin: `PackagedAutoJEIPlugin took 6768 ms`

### ISSUE THREAD

**Issue by Krutoy242** [TheLMiffy1111/PackagedAuto#52]
I found this line in my `debug.log` file:

```ruby
[Client thread/WARN] [Had Enough Items]: Sending runtime to plugin: thelm.packagedauto.integration.jei.PackagedAutoJEIPlugin took 6768 ms
```

Seems like its something wrong since usually plugins took less that 50ms to process.

[debug.log](https://github.com/TheLMiffy1111/PackagedAuto/files/14664592/debug.log)

**Comment by Krutoy242** [comment]
Found another place where it listed. There its took about 1% of whole modpack load time.

https://spark.lucko.me/1gJaCkUPrm?hl=330597

![image](https://github.com/TheLMiffy1111/PackagedAuto/assets/936618/9b21035a-86e7-4461-b2e1-2b011ce27373)

**Comment by TheLMiffy1111** [comment]
You might want to try reporting this issue to Had Enough Items

**Comment by Krutoy242** [comment]
Hmm, probably its actually HEI config issue.
I rolled back Packaged Auto and found that old versions have same several seconds lag https://spark.lucko.me/umI6BGghcl?hl=355881

This is probably related to HEI config `ultraLowMemoryUsage`. I will make more tests later.

But, if HEI is culprit here, who other mods that have HEI integration not stalled similar way? I have about 100 mods with HEI integration.

**Comment by Krutoy242** [comment]
Yes, [test](https://spark.lucko.me/OA0VRsZrKR) show that with `ultraLowMemoryUsage` set to `false` there is no `PackagedAutoJEIPlugin.onRuntimeAvailable()` called at all.

**Comment by TheLMiffy1111** [comment]
After looking at JEI code, this is probably caused by some mods modifying recipes during onRuntimeAvailable, resetting the visible category list.
Without PackagedAuto, I would guess that this stalling would probably be experienced during play when one does a first recipe search.
