### ISSUE TITLE
1.20.1 crash when switching types in the package encoder.

### ISSUE THREAD

**Issue by jusitnboggs** [TheLMiffy1111/PackagedAuto#55]
I think I was on combination when it crashed I was cycling though them.

	PackagedAuto (packagedauto), Version: 3.4.9.27

[crash-2024-11-04_12.49.55-client.txt](https://github.com/user-attachments/files/17623703/crash-2024-11-04_12.49.55-client.txt)

**Comment by TheLMiffy1111** [comment]
Remove PackagedExExCrafting, as it requires Extended Crafting: Expanded (fork of Extended Crafting with a 11x11 table) instead of the normal Extended Crafting
