### ISSUE TITLE
PackageAvaritia crashes when trying to import recipe from xei

### ISSUE THREAD

**Issue by hyperclocked333** [TheLMiffy1111/PackagedAuto#56]
[crash log](https://github.com/user-attachments/files/17789399/crash-2024-11-17_03.10.57-client.txt)
uses this forge 1.20.1 port of avaritia: https://www.curseforge.com/minecraft/mc-mods/re-avaritia
ive had zero issues with this port until now so i dont know

tried removing emi (which was originally installed) and still had the problem (the log shows the jei attempt)
in emi the recipe showed "error importing" for a brief second before crashing

sorry if its kinda vague, tell me anything if i can help anything

**Comment by TheLMiffy1111** [comment]
You might want to downgrade Re:Avaritia for now, the newest alpha version broke some compatibility

**Comment by hyperclocked333** [comment]
> You might want to downgrade Re:Avaritia for now, the newest alpha version broke some compatibility

ill try this, thank you

**Comment by hyperclocked333** [comment]
this worked, thanks for the help
