### ISSUE TITLE
Incorrect display of Encoder

### ISSUE THREAD

**Issue by GregTecher** [TheLMiffy1111/PackagedAuto#6]
![image](https://user-images.githubusercontent.com/46837124/52915629-76141900-3311-11e9-91c9-8b2dd55f75cf.png)
![image](https://user-images.githubusercontent.com/46837124/52915663-d014de80-3311-11e9-920e-74e31a15c05b.png)

**Comment by TheLMiffy1111** [comment]
Did you set recipe slots to 30? Current max is 20

**Comment by GregTecher** [comment]
well, I thought it could be more than 20...thank you.
