### ISSUE TITLE
Incorrect Caclulation of number of items needed for recipe

### ISSUE THREAD

**Issue by SeanMcMillan** [TheLMiffy1111/PackagedAuto#7]
I'm using PackagedAuto 1.0.1.4 and AE rv6-stable-6 in Enigmatica 2 Expert 1.57 to try and automate RFTools spawner to autocraft nether stars.

So my recipe is, one nether star, 5 soul sand, and 1000 melons --> 10 nether stars.

When I try to craft this, AE complains that there aren't enough melons to craft it. There are, but it seems to only count the 576 melons in the first package, and forget to account for the 424 in the second package.

If I request the two packages individually, I can request the nether star build and it will work.

(Great mod, BTW.)
![2019-03-07_21 02 16](https://user-images.githubusercontent.com/319458/54002640-5bb5aa00-411d-11e9-9c59-4a7b8f6fbd09.png)
![2019-03-07_21 02 27](https://user-images.githubusercontent.com/319458/54002641-5bb5aa00-411d-11e9-957c-a3b0f1c555aa.png)
![2019-03-07_21 02 33](https://user-images.githubusercontent.com/319458/54002643-5bb5aa00-411d-11e9-86dd-558ba8630146.png)
![2019-03-07_21 02 57](https://user-images.githubusercontent.com/319458/54002644-5bb5aa00-411d-11e9-9193-ae90bf75e98f.png)

**Comment by TheLMiffy1111** [comment]
This seems like a very old issue on AE2's side, see AppliedEnergistics/Applied-Energistics-2#439
Basically you can't have outputs in the input.

**Comment by SeanMcMillan** [comment]
Ah, so it's not miscounting the melons, it's just refusing to use a nether star to build the package that creates a nether star. Phooey. I'll test and see if it works if I change the output to something else.

**Comment by SeanMcMillan** [comment]
You were right (of course). If I change the output to something other than a nether star, it builds and runs just fine.
