### ISSUE TITLE
[Suggestion] Potential fluid autocrafting support

### ISSUE THREAD

**Issue by ArmandAgopian** [TheLMiffy1111/PackagedAuto#8]
As we all know, base AE2 doesn't support proper fluid autocrafting, but what if each "package" had a fluid tank as well from IAEStack? List the fluids it needs, and just like the package, it'll "unpack" everything and you can take it out from. I don't have time to actually write a pull request, unfortunately, but I'm putting this idea out there if anybody wants to take a crack at it. It seems like it might work.

**Comment by PizzaAddict** [comment]
+1 for this feature. it would be SUPER useful

**Comment by TheLMiffy1111** [comment]
Closed as another mod added this
