### ISSUE TITLE
[Suggestion] Add more advanced patterns

### ISSUE THREAD

**Issue by Monniasza** [TheLMiffy1111/PackagedAuto#9]
Hi, i want support for patterns of 36, 54, 72, 81, 108 and 144 items. Mockups coming soon.

**Comment by TheLMiffy1111** [comment]
Maybe try nesting packages?

**Comment by Monniasza** [comment]
I want support for both techniques.

**Comment by tod** [comment]
Can you explain how nesting packages would work? Would you have to have the unpackager ouput to a second unpackager which finally outputs to the target destination?
